### ISSUE TITLE
Questions about data sets

### ISSUE THREAD

**Issue by lxy51** [Alison-brie/MultiPropReg#2]
Hello, I wonder if it is convenient for you to provide all the data sets, and I would like to reproduce the experiment

**Comment by Alison-brie** [comment]
Here are some links, that might prove useful.

https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md
https://www.med.upenn.edu/sbia/brats2018/data.html
https://iseg2019.web.unc.edu/data/
